swagger: "2.0"
info:
  description: "Temperature station gateway generation 2 API"
  version: "1.0.0"
  title: ""
tags:
  - name: "Gen2Devices"
    externalDocs:
      description: "Find out more"
      url: "https://github.com/adamsiedlecki/OTM"
schemes:
  - "https"
  - "http"
paths:
  /sendRequest:
    post:
      tags:
        - "Gen2Devices"
      summary: "Send generic request to gateway"
      operationId: "sendGenericRequest"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "GenericMessageInput"
          description: Body of the health check request
          required: true
          schema:
            $ref: "#/definitions/GenericMessageInput"
      responses:
        "200":
          description: "Everything correct, there is a reply 4 you!"
          schema:
            $ref: "#/definitions/GenericMessageOutput"

definitions:
  GenericMessageInput:
    type: "object"
    properties:
      tg:
        description: "target"
        type: integer
      cmm:
        description: "command"
        enum:
          - tR          # temperature request
          - hC          # health check
          - hR          # humidity request
          - 10hS        # enable 10 hour sleep mode

      m:
        description: "mode"
        enum:
          - tF          # transfer - with this flag non-recipient stations will repeat the whole message
      mw:
        description: "minutesToWait" # this property is obligatory only when tF mode is enabled
        type: integer
    required:
      - tg
      - cmm

  GenericMessageOutput:
    type: "object"
    properties:
      a:
        description: "station number"
        type: integer
      tp:
        description: "temperature"
        type: number
      vol:
        description: "battery voltage"
        type: number
      hu:
        description: "humidity"
        type: number
      res:
        description: "text response"
        type: string
      error:
        description: "error"
        type: string
      m:
        description: "mode"
        enum:
          - tF # transfer - with this flag non-recipient stations will repeat the whole message